### ISSUE TITLE
Math text not rendering on blog post

### ISSUE THREAD

**Issue by coder543** [Manishearth/manishearth.github.io#3]
https://manishearth.github.io/blog/2017/03/04/what-are-sum-product-and-pi-types/

the math notations aren't working here, it would seem.

**Comment by Manishearth** [comment]
Perhaps you're blocking some JS? It works for me. Check your console.

**Comment by coder543** [comment]
Ah, right, sorry. I have uBlock Origin in advanced mode, blocking 3rd party scripts except from whitelisted domains, and everything has been working smoothly for so long after I built up my whitelist that I didn't think about that being a possible factor. I added mathjax.org to the whitelist and it works now! Sorry again.
