### ISSUE TITLE
Unicode in LB format

### ISSUE THREAD

**Issue by amitguptagwl** [Manishearth/manishearth.github.io#4]
I've just read your [post](https://manishearth.github.io/blog/2017/01/14/stop-ascribing-meaning-to-unicode-code-points/) on code points. I was wondering if you have a look at representing Unicode in [LB format](https://bigbit.github.io/bigbitjs/?text=%F0%9F%92%A9%F0%9F%98%83%F0%9F%98%AD). I would be happy to get your feedback.

**Comment by Manishearth** [comment]
I don't really see any advantages to that representation.

**Comment by amitguptagwl** [comment]
Thanks for your response. I would appreciate knowing the reason. It can help me to do the necessary changes.
