### ISSUE TITLE
Possible typo in Zero-Copy All the Things! (Zero-Copy #2) post

### ISSUE THREAD

**Issue by kw7oe** [Manishearth/manishearth.github.io#8]
Hi, I'm not sure if this is the right place to report a potential typo, please let me know otherwise. 

I notice that in the [Zero-Copy All the Things! (Zero-Copy #2)](https://manishearth.github.io/blog/2022/08/03/zero-copy-2-zero-copy-all-the-things/) post, under [Blefuscudian Bewilderment section](https://manishearth.github.io/blog/2022/08/03/zero-copy-2-zero-copy-all-the-things/#blefuscudian-bewilderment): 

> A u32 cannot be found at any old memory address, on most modern systems it must be found at a memory address that’s a multiple of 4.

Do you happen to mean `odd` memory address instead of `old`?

Anyway, thanks for the amazing writeup about zero copy in Rust 💯

**Comment by Manishearth** [comment]
Nope; ["any old X"]*(https://en.wiktionary.org/wiki/any_old) is an idiom that emphasizes "any".

**Comment by kw7oe** [comment]
Thanks for the explanation. So sorry about that 😅 English is my second language..
