### ISSUE TITLE
Broken internal links

### ISSUE THREAD

**Issue by lokegustafsson** [Manishearth/manishearth.github.io#9]
The first two links in the body of "So Zero It's ... Negative? (Zero-Copy #3)" accessed through https://manishearth.github.io/ are

* https://manishearth.github.io/zero-copy-1-not-a-yoking-matter/
* https://manishearth.github.io/zero-copy-2-zero-copy-all-the-things/

which 404. Interestingly the first two links of the same article accessed through https://manishearth.github.io/blog/2022/08/03/zero-copy-3-so-zero-its-dot-dot-dot-negative/ correctly include the date in their url :shrug:

**Comment by Manishearth** [comment]
Thanks, i'll try to fix this when I'm on the right computer.
